// Europe
// length 52
const countryCodes = [
	{name: "Slovensko",code: "SK",phone: 421},
	{name: "Alandské ostrovy",code: "AX",phone: 358},
	{name: "Albánsko",code: "AL",phone: 355},
	{name: "Andorra",code: "AD",phone: 376},
	{name: "Rakúsko",code: "AT",phone: 43},
	{name: "Bielorusko",code: "BY",phone: 375},
	{name: "Belgicko",code: "BE",phone: 32},
	{name: "Bosna a Hercegovina",code: "BA",phone: 387},
	{name: "Bulharsko",code: "BG",phone: 359},
	{name: "Chorvátsko",code: "HR",phone: 385},
	{name: "Česká republika",code: "CZ",phone: 420},
	{name: "Dánsko",code: "DK",phone: 45},
	{name: "Estónsko",code: "EE",phone: 372},
	{name: "Faerské ostrovy",code: "FO",phone: 298},
	{name: "Fínsko",code: "FI",phone: 358},
	{name: "Francúzsko",code: "FR",phone: 33},
	{name: "Nemecko",code: "DE",phone: 49},
	{name: "Gibraltár",code: "GI",phone: 350},
	{name: "Grécko",code: "GR",phone: 30},
	{name: "Guernsey",code: "GG",phone: 44},
	{name: "Svätá stolica (Vatikánsky mestský štát)",code: "VA",phone: 39},
	{name: "Maďarsko",code: "HU",phone: 36},
	{name: "Island",code: "IS",phone: 354},
	{name: "Írsko",code: "IE",phone: 353},
	{name: "ostrov Man",code: "IM",phone: 44},
	{name: "Taliansko",code: "IT",phone: 39},
	{name: "Jersey",code: "JE",phone: 44},
	{name: "Kosovo",code: "XK",phone: 383},
	{name: "Lotyšsko",code: "LV",phone: 371},
	{name: "Lichtenštajnsko",code: "LI",phone: 423},
	{name: "Litva",code: "LT",phone: 370},
	{name: "Luxembursko",code: "LU",phone: 352},
	{name: "Macedónsko, Bývalá juhoslovanská republika",code: "MK",phone: 389},
	{name: "Malta",code: "MT",phone: 356},
	{name: "Moldavská republika",code: "MD",phone: 373},
	{name: "Monako",code: "MC",phone: 377},
	{name: "Čierna Hora",code: "ME",phone: 382},
	{name: "Holandsko",code: "NL",phone: 31},
	{name: "Nórsko",code: "NO",phone: 47},
	{name: "Poľsko",code: "PL",phone: 48},
	{name: "Portugalsko",code: "PT",phone: 351},
	{name: "Rumunsko",code: "RO",phone: 40},
	{name: "San Maríno",code: "SM",phone: 378},
	{name: "Srbsko",code: "RS",phone: 381},
	{name: "Srbsko a Čierna Hora",code: "CS",phone: 381},
	{name: "Slovinsko",code: "SI",phone: 386},
	{name: "Španielsko",code: "ES",phone: 34},
	{name: "Svalbard a Jan Mayen",code: "SJ",phone: 47},
	{name: "Švédsko",code: "SE",phone: 46},
	{name: "Švajčiarsko",code: "CH",phone: 41},
	{name: "Ukrajina",code: "UA",phone: 380},
	{name: "Spojene kralovstvo",code: "GB",phone: 44}
];

export default countryCodes